apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nexus-diagnostix.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nexus-diagnostix.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "nexus-diagnostix.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        {{- include "nexus-diagnostix.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backend
      annotations:
        # Force redéploiement si ConfigMap/Secret change
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: backend
          image: "{{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag }}"
          imagePullPolicy: {{ .Values.image.backend.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "nexus-diagnostix.configmapName" . }}
            - secretRef:
                name: {{ include "nexus-diagnostix.secretName" . }}
          volumeMounts:
            - name: reports
              mountPath: /var/data/reports
            - name: ml-artifacts
              mountPath: /app/ml_artifacts
          livenessProbe:
            {{- toYaml .Values.backend.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.backend.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
      volumes:
        - name: reports
          persistentVolumeClaim:
            claimName: {{ include "nexus-diagnostix.fullname" . }}-reports
        - name: ml-artifacts
          persistentVolumeClaim:
            claimName: {{ include "nexus-diagnostix.fullname" . }}-ml
      terminationGracePeriodSeconds: 30
