apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nexus-diagnostix.fullname" . }}-ml
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nexus-diagnostix.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.backend.persistence.ml.size }}
  {{- if .Values.backend.persistence.ml.storageClass }}
  storageClassName: {{ .Values.backend.persistence.ml.storageClass }}
  {{- end }}
